### ISSUE TITLE
Change with Orientation

### ISSUE THREAD

**Issue by CJACQUEL** [jasonCodesAway/XamJam#4]
Hello, 
Width and Height does not change when the orientation of the mobile change to portrait to landscape. 

Could you help ? 
Thank you, 
Christophe

**Comment by jasonCodesAway** [comment]
I'll be happy to look into that. I can't remember what I coded up for each platform there. Is this an issue on Android, iOS, UWP, or all? Thanks! On Apr 13, 2017, at 11:47, CJACQUEL <notifications@github.com> wrote:

Hello,
Width and Height doesnot change when the orientation of the mobile change to portrait to landscape.

Could you help ?
Thank you,
Christophe

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CJACQUEL** [comment]
The issue is for Android, I use this plateform only for the moment. It is simple to reproduce, display the width the change the orientation of the screen, the width does not change.
Thx

**Comment by jasonCodesAway** [comment]
I should be able to add that functionality this weekend and hopefully cut a beta release. Are you willing to be the tester? :-)

**Comment by CJACQUEL** [comment]
Yes I can test with Android, I have no iMac. Thx.

**Comment by jasonCodesAway** [comment]
I just pushed 1.0.7. This bug should only have affected Droid. Thanks for the report! 

If you encounter any issues in testing please re-open this issue or file a new one. 

Happy Weekend :)
