### ISSUE TITLE
NETStandard version of XamJam?

### ISSUE THREAD

**Issue by dfarrNTST** [jasonCodesAway/XamJam#6]
Is there a NETStandard version of this package available or on the roadmap?  We are moving all of our library development to .NETStandard 2.0.

**Comment by jasonCodesAway** [comment]
Yes! I was just working on it last weekend. I don't have an eta yet, it'll
be my first foray into dot net standard. If all goes well it'll be out
sometime in December. With xamarin and visual studio all usually doesn't go
well (so far), so January is probably the worst case. I'll happily accept
help!


On Nov 8, 2017 at 13:20, <dfarrNTST <notifications@github.com>> wrote:

Is there a NETStandard version of this package available or on the roadmap?
We are moving all of our library development to .NETStandard 2.0.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jasonCodesAway/XamJam/issues/6>, or mute the thread

**Comment by chrisfoulds** [comment]
any update ?

**Comment by jasonCodesAway** [comment]
I've given up on Xamarin, it was just too frustratingly slow and painful. At this point XamJam is on-hold. I'm happy to accept pull requests or add anyone interested to the project or hand the project off.
